config/routes.rb
Twilio2::Application.routes.draw do
  

  root to: "clients#index"

  match '/clients/sms/:id' => 'clients#sms', as: :sms_client
  match '/clients/makecall/:id' => 'clients#makecall', as: :makecall_client
  match '/clients/speak/:id' => 'clients#speak', as: :speak_client
resources :clients

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :message, :phone, :name, :voice
  validates :name, presence: true
  validates :message, presence: true
  validates :phone, phone_number: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  require 'uri'
  Twilio_sid = 'ACee185e4fdf1ff6dac321d90841f23f25'
  Twilio_token = ''
  Twilio_phone_number = "6479311279"
  BASE_URL= 'localhost:3000/clients'
  def sms
    @client = Client.find(params[:id])
    
    @twilio_client = Twilio::REST::Client.new Twilio_sid, Twilio_token
 
    @twilio_client.account.sms.messages.create(
      :from => "+1#{Twilio_phone_number}",
      :to => @client.phone,
      :body => @client.message[0..139]
    )
  end

  def makecall
    @client = Client.find(params[:id])
    @url='http://twimlets.com/message?Message%5B0%5D=' + ERB::Util.url_encode( ',,Hello' + @client.name+',,' + @client.message) 
    @url = @url + '&Message%5B1%5D=http%3A%2F%2Foccam.md%2Fhs.mp3&'
    begin
      @twilio_client = Twilio::REST::Client.new Twilio_sid, Twilio_token
      @twilio_client.account.calls.create(
      :from => "+1#{Twilio_phone_number}",
      :to => @client.phone,
      :url => @url
      )
    rescue StandardError => bang
      redirect_to :action => '.', 'msg' => "Error #{bang}"
      return
    end
 
  end
# TwiML response that reads the reminder to the caller and presents a
# short menu: 1. repeat the msg, 2. directions, 3. goodbye
  def speak
    response = Twilio::TwiML::Response.new do |r|
  r.Say 'hello there', :voice => 'woman'
  end
  @xml=response.text
end



  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end

  end

  
  
  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_path, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to clients_path, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client, html: {class: "form-horizontal"}) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    Name<br/>
    <%= f.text_field :name, class: 'input-xlarge' %>
  </div>
  <div class="field">
    Phone<br />
    <%= f.text_field :phone, class: 'input-xlarge' %>
  </div>
  <div class="field">
   Voice<br />
    <%= f.text_field :voice, class: 'input-xlarge' %>
  </div>
  <div class="field">
    Message<br />
    <%= f.text_field :message, class: 'input-xlarge' %>
  </div>
  <div class="form">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path, class:"btn btn-large btn-primary" %>

app/views/clients/index.html.erb
<h4 style="color:red;">Thanks to HackerYou and Ruby Brigade!</h4>
<lead>Click 'Add Your Phone!' to try it out.  SMS will send the message to the phone, Call & Speak will dial the number and convert the text to speech.</lead>


<table class="table table-striped table-bordered">
  <tr style="text-align:center">
    <th>Name</th>
    <th>Phone</th>
    <th>Message</th>
    <th>Voice</th>
    <th style="text-align:centre;">Actions</th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.phone %></td>
    <td><%= client.message %></td>
    <td><%= client.voice %></td>
    <td >
    <%= link_to 'Edit', edit_client_path(client) , class: "btn" %>
    <%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn"  %>
    <%= link_to 'SMS', sms_client_path(client), class: "btn btn-success"  %>
    <%= link_to 'Call & Speak', makecall_client_path(client), class: "btn btn-danger" %></td>
 
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add Your Phone!', new_client_path, class:"btn btn-large btn-primary" %>

app/views/clients/makecall.html.erb
<h4>'<%= @client.message %>' spoken to <%= @client.phone %>!</h4>

<br/>
<br/>

<%= link_to 'Back', clients_path, class:"btn btn-large btn-primary" %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path, class:"btn btn-large btn-primary" %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Phone:</b>
  <%= @client.phone %>
</p>

<p>
  <b>Message:</b>
  <%= @client.message %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path, class:"btn btn-large btn-primary"%>

app/views/clients/sms.html.erb
<h4>'<%= @client.message %>' was sent to <%= @client.phone %>!</h4>
<br/>
<br/>

<%= link_to 'Back', clients_path, class:"btn btn-large btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twilio2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button> 
          <a id="logo" class="brand" href="/">
              <%= image_tag('twilio.png') %> Twilio Hack Night
          </a>

          <div class="nav-collapse collapse">
            <ul class="nav pull-right">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
</head>
<body>   
	
<div class="container-responsive">
<%= yield %>
</div>

</body>
</html>